services:
  db:
    image: mariadb:latest
    container_name: mariadb_trt
    restart: always
    environment:
      MARIADB_USER: LOCAL_ADMIN
      MARIADB_PASSWORD: "abc123."
      MARIADB_DATABASE: theroundtable
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - trt-net

networks:
  trt-net:
    driver: bridge
